### PR TITLE
Updated LMU

### PR DESCRIPTION
**Pull request by Skrupellos**

### CODE REVIEW

**Comment by mswart** [comment]
Thanks for the update. I will hopefully tomorrow find time to check/merge change, update the parser and create/archive the canteens in OpenMensa. I will inform you if it is done.

**Comment by mswart** [comment]
New canteens are:

* https://openmensa.org/c/229
* https://openmensa.org/c/230
* https://openmensa.org/c/231
* https://openmensa.org/c/232

It would be very helpful if you could check whether the canteen locations are correct.

Again many thanks for this correction.

**Comment by Skrupellos** [comment]
https://openmensa.org/c/232 is located here: http://www.openstreetmap.org/?mlat=48.14275&mlon=11.56854#map=19/48.14275/11.56854
All other locations are accurate enough :)

A complete map can be found here: http://www.studentenwerk-muenchen.de/mensa/unsere-mensen-und-stucafes/muenchen/

**Comment by mswart** [comment]
thx, is corrected.

**Pull request merged**
