### PR TITLE
wuerzburg: added "Mensateria" to existing wuerzburg parser

### PR DESCRIPTION
**Pull request by pstiegele**
In Würzburg has opened a new mensa. I added it to the existing parser, hope it works that way.

### CODE REVIEW

**Comment by klemens** [comment]
Thank you for your contribution and sorry for talking so long.

> I added it to the existing parser, hope it works that way.

Yes, that is the first step! :wink: It seems `mensateria-campus-nord.html` is now called (and redirected to) `mensateria-campus-hubland-nord-wuerzburg.html`. It seems to work fine with the existing parser based on my limited testing (although there is potential for general improvement of the parser).

I also noticed that there are some other changes in Würzburg:
* `burse-wuerzburg.html` is now called `burse-am-studentenhaus-wuerzburg.html`
* `frankenstube-wuerzburg.html` and `mensa-am-hubland-wuerzburg.html` don't exist anymore. Do you know more?
* `mensa-aschaffenburg` is somehow missing the `.html`

If you want, you can add these changes to your pull request, otherwise I can also make them afterwards.

**Comment by pstiegele** [comment]
Hey, I updated the links. Frankenstube and Mensa am Hubland are closed for the next year 'cause of a renovation, that's why there are two new mensas. 
Can't test it, but it should work.

**Comment by klemens** [comment]
Thanks, this is now merged! I also added a few changes to fix the parsing of prices and additives: c25be2ef647034043a32e4d113e4481a9783ae08

It will probably take a little while before these changes are visible on openmensa.org.

**Comment by klemens** [comment]
I just added the three new canteens, frankenstube and hubland were already disabled.

* https://openmensa.org/c/830
* https://openmensa.org/c/259
* https://openmensa.org/c/831

These should start working tomorrow.

**Pull request merged**
