### PR TITLE
niederbayern-oberpfalz: Update legend

### PR DESCRIPTION
**Pull request by shad0w73**
The legend has been expanded.

### CODE REVIEW

**Comment by shad0w73** [comment]
What am I missing at the travis ci check?

**Comment by klemens** [comment]
The Travis fail is unrelated (the dresden/reichenbachstrasse parser returned a 500), I'll have a look.

**Comment by shad0w73** [comment]
Ok, thanks ^^

**Comment by klemens** [comment]
I fixed the dresden error and rebased your branch onto the fix. Thank you!

A technical note: Please don't use the master branch of your fork for pull requests, as this can make updating of your master for a future change more difficult.

**Pull request merged**
