### PR TITLE
Fix meal data extraction

### PR DESCRIPTION
**Pull request by JensWinter**

### CODE REVIEW

**Comment by JensWinter** [comment]
Don't understand why the build is failing. What's happening here?
Can someone help?

**Comment by klemens** [comment]
The build failed because of the `muenchen` parser, so this is unrelated to your pull request.

**Comment by JensWinter** [comment]
Ah! Thanks @klemens. Didn't recognize the error output there.

**Comment by klemens** [comment]
I fixed the `muenchen` parser (d8fe856c10b8adf20800c3ddcddc51bb2890417e), so you can rebase and check again!

**Pull request merged**
